language: erlang
otp_release:
  - 21.3
  - 22.3
  - 23.0
install:
  - mkdir -p ~/.config/rebar3/
  - echo "{plugins, [rebar3_proper]}. {deps, [proper]}." > ~/.config/rebar3/rebar.config
  - make
script:
  - make test
  - make proper
  - make coverage
  - ./rebar3 as test coveralls send
  - make dialyzer
  - make lint
  - make xref
sudo: required
dist: trusty
