language: erlang
otp_release:
  - 22.3
  - 23.0
  - 23.3
  - 24.0
install:
  - make
script:
  - make test
  - make proper
  - make coverage
  - ./rebar3 as test coveralls send
  - make dialyzer
  - make lint
  - make xref
sudo: required
dist: trusty
