language: erlang
otp_release:
  - 21.3
  - 22.3
  - 23.0
install:
  - mkdir -p ~/.config/rebar3/
  - echo "{plugins, [{rebar3_proper, \"0.12.0\"}]}." > ~/.config/rebar3/rebar.config
  - echo "{deps, [{proper, \"1.3.0\"}]}." > ~/.config/rebar3/rebar.config
  - make
  - ./rebar3 update
script:
  - make test
  - make proper
  - make coverage
  - ./rebar3 as test coveralls send
  - make dialyzer
  - make lint
  - make xref
sudo: required
dist: trusty
